# EvalHub Client — Local LightEval Evaluation

This notebook walks through the full evaluation lifecycle using EvalHub in local mode: connecting to the server, submitting an evaluation job, monitoring progress, and inspecting results in MLflow and the OCI registry.

**Steps:**

1. **Connect to EvalHub** — verify the server is healthy
2. **Discover providers and benchmarks** — list what is available for evaluation
3. **Verify model availability** — confirm the LLM endpoint is serving the target model
4. **Submit an evaluation job** — configure and submit a GSM8K benchmark run
5. **Monitor job progress** — poll until the job completes or fails
6. **Inspect results** — review the job response, MLflow experiment runs, and OCI artifacts
7. **Cleanup** — delete the job from the server

> **Kernel:** Select `.venv/bin/python` as the Jupyter kernel.
> **Prerequisites:** See `readme.md` for the setup required before running this notebook.

In [1]:
from evalhub import (
    SyncEvalHubClient,
    JobSubmissionRequest,
    BenchmarkConfig,
    ModelConfig,
    JobStatus,
    ExperimentConfig,
    EvaluationExports,
    EvaluationExportsOCI,
    OCICoordinates,
)
import os

## 1. Connect to EvalHub

In [2]:
evalhub_url = "http://localhost:8080"
client = SyncEvalHubClient(base_url=evalhub_url)
health = client.health()
print(f"✓ EvalHub is healthy: {health['status']}")

✓ EvalHub is healthy: healthy

## 2. Discover providers and benchmarks

### 2.1 List providers

In [3]:
providers = client.providers.list()
print(f"✓ Found {len(providers)} providers:")
for provider in providers:
    print(f"  - {provider.resource.id}: {provider.name}")

✓ Found 1 providers:
  - lighteval: LightEval

### 2.2 List benchmarks

In [4]:
provider_id = "lighteval"

In [5]:
benchmarks = client.benchmarks.list(provider_id=provider_id)
print(f"\n✓ Found {len(benchmarks)} benchmarks for {provider_id}:")
for benchmark in benchmarks:
    print(f"  - {benchmark.id}: {benchmark.name}")

✓ Found 1 benchmarks for lighteval:
  - gsm8k: Grade-school math word problems

## 3. Verify model availability

In [6]:
model_url = "http://localhost:11434/v1"
model_name = "llama3.2:3b-instruct-q4_K_M"

In [7]:
import requests

response = requests.get(f"{model_url}/models")
models = response.json()
model_info = next(m for m in models["data"] if m["id"] == model_name)
print(model_info)

{'id': 'llama3.2:3b-instruct-q4_K_M', 'object': 'model', 'created': 1778599771, 'owned_by': 'library'}

## 4. Submit an evaluation job

Configure the job parameters — model, benchmark, experiment tracking, and OCI export — then submit.

In [8]:
# evalhub
job_name = "ev-job1"
benchmark_id = "gsm8k"

# mlflow
experiment_name = "ev-exp1"

# oci
oci_host = "localhost:5001"
oci_repository = "eval-results"

In [9]:
from evalhub import ExperimentTag

job_request = JobSubmissionRequest(
    name=job_name,
    model=ModelConfig(url=model_url, name=model_name),
    benchmarks=[
        BenchmarkConfig(
            id=benchmark_id,
            provider_id=provider_id,
            parameters={
                "num_examples": 10,  # Number of examples to evaluate
                "num_few_shot": 0,
            },
        )
    ],
    experiment=ExperimentConfig(
        name=experiment_name,
        description=f"Local LightEval evaluation experiment for {model_name}",
        tags=[
            ExperimentTag(key="model", value=model_name),
            ExperimentTag(key="provider_id", value=provider_id),
        ],
    ),
    exports=EvaluationExports(
        oci=EvaluationExportsOCI(
            coordinates=OCICoordinates(
                oci_host=oci_host,
                oci_repository=oci_repository,
                annotations={
                    "job_name": job_name,
                    "experiment_name": experiment_name,
                },
            )
        )
    ),
)

# Submit job using nested resource
job = client.jobs.submit(job_request)

# Store job ID for later use
job_id = job.id
print(f"✓ Job submitted successfully")
print(f"  Job ID: {job_id}")
print(f"  State: {job.state}")
print(f"  Created: {job.resource.created_at}\n")
print(job.model_dump_json(indent=2))

✓ Job submitted successfully
  Job ID: 9c9cc498-0a18-419c-9026-f700b538e8da
  State: JobStatus.PENDING
  Created: 2026-05-13 14:01:56.835518+05:30

{
  "resource": {
    "id": "9c9cc498-0a18-419c-9026-f700b538e8da",
    "tenant": null,
    "created_at": "2026-05-13T14:01:56.835518+05:30",
    "updated_at": null,
    "mlflow_experiment_id": "1",
    "message": null
  },
  "status": {
    "state": "pending",
    "message": {
      "message": "Evaluation job created",
      "message_code": "evaluation_job_created"
    },
    "benchmarks": []
  },
  "results": {
    "benchmarks": [],
    "mlflow_experiment_url": "http://localhost:5000/api/2.0/mlflow/experiments"
  },
  "name": "ev-job1",
  "description": null,
  "tags": [],
  "model": {
    "url": "http://localhost:11434/v1",
    "name": "llama3.2:3b-instruct-q4_K_M",
    "auth": null
  },
  "benchmarks": [
    {
      "id": "gsm8k",
      "provider_id": "lighteval",
      "parameters": {
        "num_examples": 10,
        "num_few_shot": 0
      },
      "test_data_ref": null
    }
  ],
  "collection": null,
  "experiment": {
    "name": "ev-exp1",
    "tags": [
      {
        "key": "model",
        "value": "llama3.2:3b-instruct-q4_K_M"
      },
      {
        "key": "provider_id",
        "value": "lighteval"
      }
    ],
    "artifact_location": null
  },
  "exports": {
    "oci": {
      "coordinates": {
        "oci_host": "localhost:5001",
        "oci_repository": "eval-results",
        "oci_tag": null,
        "oci_subject": null,
        "annotations": {
          "experiment_name": "ev-exp1",
          "job_name": "ev-job1"
        }
      },
      "k8s": null
    }
  },
  "queue": null
}

## 5. Monitor job progress

Poll the job status until it completes or fails.

In [10]:
import time

updated_job = client.jobs.get(job_id=job_id)

while updated_job.state not in (JobStatus.COMPLETED, JobStatus.FAILED):
    print(f"\n✓ Current job state: {updated_job.state}")
    time.sleep(5)
    updated_job = client.jobs.get(job_id=job_id)

if updated_job.state == JobStatus.FAILED:
    if updated_job.status and updated_job.status.message:
        print(f"Job failed: {updated_job.status.message.message}")
    else:
        print("Job failed: Unknown")
else:
    print(f"✓ Job completed successfully: {updated_job.state}")

✓ Current job state: JobStatus.RUNNING

✓ Current job state: JobStatus.RUNNING

✓ Current job state: JobStatus.RUNNING

✓ Current job state: JobStatus.RUNNING

✓ Current job state: JobStatus.RUNNING

✓ Current job state: JobStatus.RUNNING
✓ Job completed successfully: JobStatus.COMPLETED

## 6. Inspect results

### 6.1 Completed job response

In [12]:
print(updated_job.model_dump_json(indent=2))

{
  "resource": {
    "id": "9c9cc498-0a18-419c-9026-f700b538e8da",
    "tenant": null,
    "created_at": "2026-05-13T08:31:56Z",
    "updated_at": "2026-05-13T08:32:25Z",
    "mlflow_experiment_id": "1",
    "message": null
  },
  "status": {
    "state": "completed",
    "message": {
      "message": "Evaluation job is completed",
      "message_code": "evaluation_job_updated"
    },
    "benchmarks": [
      {
        "id": "gsm8k",
        "provider_id": "lighteval",
        "benchmark_index": 0,
        "status": "completed",
        "error_message": null,
        "started_at": null,
        "completed_at": "2026-05-13T08:32:24.897553Z"
      }
    ]
  },
  "results": {
    "benchmarks": [
      {
        "id": "gsm8k",
        "provider_id": "lighteval",
        "benchmark_index": 0,
        "metrics": {
          "all.extractive_match": 0.7,
          "gsm8k|0.extractive_match": 0.7
        },
        "artifacts": {
          "evalhub.env_card": {
            "aggregate_results": {},
            "autograder_bias": {},
            "capture_completeness": 0.15,
            "confidence_intervals": {},
            "cpu_model": "arm",
            "custom": {},
            "k8s_pod_labels": {},
            "k8s_resource_limits": {},
            "key_packages": {
              "mlflow": "3.11.1",
              "torch": "2.11.0",
              "transformers": "5.8.1"
            },
            "os_info": "macOS-26.4.1-arm64-arm-64bit",
            "per_task_results": {},
            "python_version": "3.12.12",
            "scorer_ids": []
          },
          "oci_digest": "sha256:34e99e53297e41601124256eabd123b721084b380ca63b64ccec7b28f084f078",
          "oci_reference": "localhost:5001/eval-results:evalhub-b5c38938e0f23bb70ee4b125d52f5e3b55a23abd710f08a719213de593f7a233@sha256:34e99e53297e41601124256eabd123b721084b380ca63b64ccec7b28f084f078"
        },
        "mlflow_run_id": "41d4fb940bf743d384c2f12ab891abe1",
        "logs_path": null
      }
    ],
    "mlflow_experiment_url": "http://localhost:5000/api/2.0/mlflow/experiments"
  },
  "name": "ev-job1",
  "description": null,
  "tags": [],
  "model": {
    "url": "http://localhost:11434/v1",
    "name": "llama3.2:3b-instruct-q4_K_M",
    "auth": null
  },
  "benchmarks": [
    {
      "id": "gsm8k",
      "provider_id": "lighteval",
      "parameters": {
        "num_examples": 10,
        "num_few_shot": 0
      },
      "test_data_ref": null
    }
  ],
  "collection": null,
  "experiment": {
    "name": "ev-exp1",
    "tags": [
      {
        "key": "model",
        "value": "llama3.2:3b-instruct-q4_K_M"
      },
      {
        "key": "provider_id",
        "value": "lighteval"
      }
    ],
    "artifact_location": null
  },
  "exports": {
    "oci": {
      "coordinates": {
        "oci_host": "localhost:5001",
        "oci_repository": "eval-results",
        "oci_tag": null,
        "oci_subject": null,
        "annotations": {
          "experiment_name": "ev-exp1",
          "job_name": "ev-job1"
        }
      },
      "k8s": null
    }
  },
  "queue": null
}

### 6.2 MLflow experiment runs

Query MLflow for the experiment runs created by the evaluation job.

In [13]:
import mlflow

mlflow_url = "http://localhost:5000"

mlflow.set_tracking_uri(mlflow_url)
runs = mlflow.search_runs(search_all_experiments=True)

print(runs.columns.tolist())

['run_id', 'experiment_id', 'status', 'artifact_uri', 'start_time', 'end_time', 'metrics.all.extractive_match', 'metrics.gsm8k_0.extractive_match', 'metrics.overall_score', 'params.model_name', 'params.num_examples_evaluated', 'params.duration_seconds', 'params.benchmark_id', 'tags.mlflow.runName', 'tags.provider_id', 'tags.model']

In [14]:
runs

,run_id,experiment_id,status,artifact_uri,start_time,end_time,metrics.all.extractive_match,metrics.gsm8k_0.extractive_match,metrics.overall_score,params.model_name,params.num_examples_evaluated,params.duration_seconds,params.benchmark_id,tags.mlflow.runName,tags.provider_id,tags.model
0,41d4fb940bf743d384c2f12ab891abe1,1,FINISHED,mlflow-artifacts:/1/41d4fb940bf743d384c2f12ab8...,2026-05-13 08:32:24.956000+00:00,2026-05-13 08:32:24.968000+00:00,0.7,0.7,0.7,llama3.2:3b-instruct-q4_K_M,10,27.666032075881958,gsm8k,9c9cc498-0a18-419c-9026-f700b538e8da,lighteval,llama3.2:3b-instruct-q4_K_M

In [15]:
cols = [
    c
    for c in runs.columns
    if c.startswith(("metrics.", "params."))
    or c in ("run_id")
]
runs[cols].head()

,run_id,metrics.all.extractive_match,metrics.gsm8k_0.extractive_match,metrics.overall_score,params.model_name,params.num_examples_evaluated,params.duration_seconds,params.benchmark_id
0,41d4fb940bf743d384c2f12ab891abe1,0.7,0.7,0.7,llama3.2:3b-instruct-q4_K_M,10,27.666032075881958,gsm8k

### 6.3 OCI artifacts

Verify that the evaluation results were pushed to the OCI registry.

In [16]:
oci_reference = updated_job.results.benchmarks[0].artifacts["oci_reference"]
print(f"oci_reference: {oci_reference}")

oci_reference: localhost:5001/eval-results:evalhub-b5c38938e0f23bb70ee4b125d52f5e3b55a23abd710f08a719213de593f7a233@sha256:34e99e53297e41601124256eabd123b721084b380ca63b64ccec7b28f084f078

In [17]:
from oras.client import OrasClient

oras_client = OrasClient(insecure=True)

# Fetch manifest for the experiment tag
manifest = oras_client.get_manifest(oci_reference)
import pprint
pprint.pprint(manifest)

{'annotations': {'experiment_name': 'ev-exp1',
                 'io.github.eval-hub.benchmark': 'gsm8k',
                 'io.github.eval-hub.benchmark_id': 'gsm8k',
                 'io.github.eval-hub.job_id': '9c9cc498-0a18-419c-9026-f700b538e8da',
                 'io.github.eval-hub.model': 'llama3.2:3b-instruct-q4_K_M',
                 'io.github.eval-hub.provider_id': 'lighteval',
                 'job_name': 'ev-job1',
                 'org.opencontainers.image.created': '2026-05-13T08:32:24.820805+00:00'},
 'artifactType': 'application/vnd.eval-hub.github.io',
 'config': {'digest': 'sha256:90977d9e890e3322e05811e768da4681520956cd097030fcd797c46b77ff0ee3',
            'mediaType': 'application/vnd.oci.image.config.v1+json',
            'size': 609},
 'layers': [{'annotations': {'olot.layer.content.name': 'lighteval_results.json'},
             'digest': 'sha256:2f10dc978de7cc8435948bae0f21d0fe84d77123ea02b8736ebd256554b11796',
             'mediaType': 'application/vnd.oci.image.layer.v1.tar+gzip',
             'size': 1581},
            {'annotations': {'olot.layer.content.name': 'results.json'},
             'digest': 'sha256:a6271c0831ca2c38b7cf6d7040014226d004fbcf91b1835de086a949e436b223',
             'mediaType': 'application/vnd.oci.image.layer.v1.tar+gzip',
             'size': 509},
            {'annotations': {'olot.layer.content.name': 'summary.txt'},
             'digest': 'sha256:12b3d4e0a84aa3a8f398dce79721a9fcc6299487f2d547af4973e710c5b916c1',
             'mediaType': 'application/vnd.oci.image.layer.v1.tar+gzip',
             'size': 382}],
 'mediaType': 'application/vnd.oci.image.manifest.v1+json',
 'schemaVersion': 2}

#### 6.3.1 Inspect layer contents

In [19]:
import tarfile
import io
import json

for i, layer in enumerate(manifest["layers"], start=1):
    name = layer.get("annotations", {}).get("olot.layer.content.name", "unknown")
    response = oras_client.get_blob(f"{oci_host}/{oci_repository}", layer["digest"])

    print(f"=== {i}. {name} ===")
    try:
        tar = tarfile.open(fileobj=io.BytesIO(response.content))
        for member in tar.getmembers():
            f = tar.extractfile(member)
            if f:
                content = f.read().decode("utf-8")
                if member.name.endswith(".json"):
                    print(json.dumps(json.loads(content), indent=2))
                else:
                    print(content)
        tar.close()
    except tarfile.TarError:
        print(response.text)
    print()

=== 1. lighteval_results.json ===
{
  "config_general": {
    "lighteval_sha": "?",
    "num_fewshot_seeds": 1,
    "max_samples": 10,
    "job_id": "0",
    "start_time": 571903.2454825,
    "end_time": 571911.55315025,
    "total_evaluation_time_secondes": "8.307667750050314",
    "model_config": {
      "model_name": "openai/llama3.2:3b-instruct-q4_K_M",
      "generation_parameters": {
        "num_blocks": null,
        "block_size": null,
        "early_stopping": null,
        "repetition_penalty": null,
        "frequency_penalty": null,
        "length_penalty": null,
        "presence_penalty": null,
        "max_new_tokens": null,
        "min_new_tokens": null,
        "seed": null,
        "stop_tokens": null,
        "temperature": 0,
        "top_k": null,
        "min_p": null,
        "top_p": null,
        "truncate_prompt": null,
        "cache_implementation": null,
        "response_format": null
      },
      "system_prompt": null,
      "cache_dir": "~/.cache/huggingface/lighteval",
      "provider": null,
      "base_url": "http://localhost:11434/v1",
      "api_key": "dummy",
      "concurrent_requests": 10,
      "verbose": false,
      "max_model_length": null,
      "api_max_retry": 8,
      "api_retry_sleep": 1.0,
      "api_retry_multiplier": 2.0,
      "timeout": null
    },
    "model_name": "openai/llama3.2:3b-instruct-q4_K_M"
  },
  "results": {
    "gsm8k|0": {
      "extractive_match": 0.7,
      "extractive_match_stderr": 0.15275252316519466
    },
    "all": {
      "extractive_match": 0.7,
      "extractive_match_stderr": 0.15275252316519466
    }
  },
  "versions": {},
  "config_tasks": {
    "gsm8k|0": {
      "name": "gsm8k",
      "prompt_function": "gsm8k_prompt",
      "hf_repo": "openai/gsm8k",
      "hf_subset": "main",
      "metrics": [
        {
          "metric_name": "extractive_match",
          "higher_is_better": true,
          "category": "GENERATIVE",
          "sample_level_fn": "MultilingualExtractiveMatchMetric(language=Language.ENGLISH, gold_extraction_target=(ExprExtractionConfig(try_extract_without_anchor=True),), pred_extraction_target=(ExprExtractionConfig(try_extract_without_anchor=True), LatexExtractionConfig(try_extract_without_anchor=True, boxed_match_priority=0, normalization_config=NormalizationConfig(basic_latex=True, units=True, malformed_operators=True, nits=True, boxed='all', equations=True))), aggregation_function=max, fallback_mode=first_match, extraction_mode=any_match, precision=5, timeout_seconds=5)",
          "corpus_level_fn": "mean",
          "batched_compute": false
        }
      ],
      "solver": [
        "solve",
        "solve"
      ],
      "scorer": "score",
      "sample_fields": "record_to_sample",
      "sample_to_fewshot": "sample_to_fewshot",
      "filter": null,
      "hf_revision": null,
      "hf_filter": null,
      "hf_avail_splits": [
        "train",
        "test"
      ],
      "evaluation_splits": [
        "test"
      ],
      "few_shots_split": null,
      "few_shots_select": "random_sampling_from_train",
      "generation_size": 256,
      "generation_grammar": null,
      "stop_sequence": [
        "Question:"
      ],
      "num_samples": null,
      "original_num_docs": -1,
      "effective_num_docs": -1,
      "must_remove_duplicate_docs": false,
      "num_fewshots": 0,
      "version": 0
    }
  },
  "summary_tasks": {
    "gsm8k|0": {
      "hashes": {
        "hash_examples": "34eb3ecbbd9b0f5b",
        "hash_full_prompts": "ef46db3751d8e999",
        "hash_input_tokens": "a7788e9d8e45e7a3",
        "hash_cont_tokens": "a7788e9d8e45e7a3"
      },
      "truncated": 0,
      "non_truncated": 0,
      "padded": 0,
      "non_padded": 0
    }
  },
  "summary_general": {
    "hashes": {
      "hash_examples": "c65776f786de579a",
      "hash_full_prompts": "c166e5d20ad58f4e",
      "hash_input_tokens": "dc1c46bc6d4d2cb8",
      "hash_cont_tokens": "dc1c46bc6d4d2cb8"
    },
    "truncated": 0,
    "non_truncated": 0,
    "padded": 0,
    "non_padded": 0
  }
}

=== 2. results.json ===
{
  "job_id": "9c9cc498-0a18-419c-9026-f700b538e8da",
  "benchmark_id": "gsm8k",
  "model_name": "llama3.2:3b-instruct-q4_K_M",
  "framework": "lighteval",
  "results": [
    {
      "metric_name": "gsm8k|0.extractive_match",
      "metric_value": 0.7,
      "metric_type": "float",
      "confidence_interval": [
        0.4006050545962184,
        0.9993949454037815
      ],
      "num_samples": null,
      "metadata": {
        "task": "gsm8k|0",
        "metric": "extractive_match",
        "stderr": 0.15275252316519466
      }
    },
    {
      "metric_name": "all.extractive_match",
      "metric_value": 0.7,
      "metric_type": "float",
      "confidence_interval": [
        0.4006050545962184,
        0.9993949454037815
      ],
      "num_samples": null,
      "metadata": {
        "task": "all",
        "metric": "extractive_match",
        "stderr": 0.15275252316519466
      }
    }
  ]
}

=== 3. summary.txt ===
LightEval Evaluation Results
======================================================================

Job ID: 9c9cc498-0a18-419c-9026-f700b538e8da
Benchmark: gsm8k
Model: llama3.2:3b-instruct-q4_K_M

Metrics:
----------------------------------------------------------------------
gsm8k|0.extractive_match: 0.7
  95% CI: (0.4006050545962184, 0.9993949454037815)
all.extractive_match: 0.7
  95% CI: (0.4006050545962184, 0.9993949454037815)

## 7. Cleanup

In [20]:
client.jobs.cancel(job_id=job_id, hard_delete=True)

True